### ISSUE TITLE
Execstack warning

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [ericoporto/pyqthelloworld#2]
```
Priming pyqthelloworld 

<stripped>

The execstacks are going to be cleared for the following files:
- /home/ubuntu/pyqthelloworld/prime/lib/python3.5/site-packages/PyQt5/Qt/lib/libQt5WebEngineCore.so.5
To disable this behavior set `build-attributes: [keep-execstack]` for the part.
```

Refer [Snap and executable stacks - doc - snapcraft.io](https://forum.snapcraft.io/t/snap-and-executable-stacks/1812) for more info about this issue.  The solution might be to avoid staging the library with execstack as we unlikely depending on it.

**Comment by ericoporto** [comment]
Let me see if I understood that. Apparently the current python3 qt5 package in ubuntu is including webkit and other web related things. Then `libQt5WebEngineCore` apparently has execstack on. You are saying me it probably isn't needed (I can't verify since I don't use it, but I feel it should be working if someone uses it someday™). I will disable the exec stack to instead of removing from staging which appears to be the solution proposed in the links.
